---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    fabric8.io/git-commit: 3279e9bcf74f0f2ef56a583d35535624cf88a5bc
    fabric8.io/git-branch: migrate-workshop
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=backend-v2&var-version=2.0
  labels:
    app: backend-v2
    provider: fabric8
    version: "2.0"
    group: org.jboss.examples.eap
  name: backend-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-v2
      provider: fabric8
      group: org.jboss.examples.eap
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: 3279e9bcf74f0f2ef56a583d35535624cf88a5bc
        fabric8.io/git-branch: migrate-workshop
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=backend-v2&var-version=2.0
      labels:
        service: backend
        app: backend-v2
        provider: fabric8
        version: "2.0"
        group: org.jboss.examples.eap
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: ceposta/backend-mysql:v2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /rest/ping
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        name: ceposta-backend-v2
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /rest/ping
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        securityContext:
          privileged: false
