spec:
  template:
    metadata:
      labels:
        service: backend
    spec:
      containers:
      - livenessProbe:
          httpGet:
            path: /rest/ping
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /rest/ping
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
