---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-orders
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ticketmonster
        component: orders
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: admin
        - name: MYSQL_DATABASE
          value: orders
        - name: MYSQL_USER
          value: ticket
        - name: MYSQL_PASSWORD
          value: monster
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
          - name: mysql-config
            mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: mysql-config
          configMap:
            name: orders-mysql-config

