---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: d274512765d69ebdd100ca68c1180a7a2bc59753
    fabric8.io/iconUrl: img/icons/spring-boot.svg
    fabric8.io/git-branch: migrate-workshop
    prometheus.io/scrape: "true"
    prometheus.io/port: "9779"
  labels:
    expose: "true"
    app: orders-service
    provider: fabric8
    version: 1.0.0-SNAPSHOT
    group: org.ticketmonster.orders
  name: orders-service
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: orders-service
    provider: fabric8
    group: org.ticketmonster.orders
